---
default_set: 'centos-64-x64'
sets:
  'centos-64-x64':
    nodes:
      'single.centos':
        prefab: 'centos-64-x64'
  'debian-70rc1-x64':
    nodes:
      'single.debian':
        prefab: 'debian-70rc1-x64'
